version: '3.1'
services:
    pg: 
        image: postgres:10-alpine
        ports:
           - "5435:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
    admin:
        image: adminer
        restart: always
        links: 
            - pg:db
        ports:
            - 8081:8080